// tasks
export const GET_TASKS = "GET_TASKS";
export const GET_TASKS_START = "GET_TASKS_START";
export const GET_TASKS_COMPLETE = "GET_TASKS_COMPLETE";
export const GET_TASKS_FAILED = "GET_TASKS_FAILED";

export const GET_COMPLETED_TASKS = "GET_COMPLETED_TASKS";

export const GET_TOTAL_COUNT = "GET_TOTAL_COUNT";
export const GET_TOTAL_COUNT_COMPLETE = "GET_TOTAL_COUNT_COMPLETE";
export const GET_TOTAL_COUNT_FAILED = "GET_TOTAL_COUNT_FAILED";

export const ADD_TASK = "ADD_TASK";
export const ADD_TASK_COMPLETE = "ADD_TASK_COMPLETE";
export const ADD_TASK_FAILED = "ADD_TASK_FAILED";

export const DELETE_TASK = "DELETE_TASK";
export const DELETE_TASK_COMPLETE = "DELETE_TASK_COMPLETE";
export const DELETE_TASK_FAILED = "DELETE_TASK_FAILED";

export const EDIT_TASK = "EDIT_TASK";
export const EDIT_TASK_COMPLETE = "EDIT_TASK_COMPLETE";
export const EDIT_TASK_FAILED = "EDIT_TASK_FAILED";

export const COMPLETE_TASK = "COMPLETE_TASK";
export const UNCOMPLETE_TASK = "UNCOMPLETE_TASK";

export const REARRANGE_TASKS = "REARRANGE_TASKS";
export const REARRANGE_TASKS_START = "REARRANGE_TASKS_START";
export const REARRANGE_TASKS_COMPLETE = "REARRANGE_TASKS_COMPLETE";
export const REARRANGE_TASKS_FAILED = "REARRANGE_TASKS_FAILED";

export const SHOW_ADD_FORM = "SHOW_ADD_FORM";
export const HIDE_ADD_FORM = "HIDE_ADD_FORM";
export const SHOW_EDIT_FORM = "SHOW_EDIT_FORM";
export const HIDE_EDIT_FORM = "HIDE_EDIT_FORM";
export const SHOW_DELETE_CONFIRM = "SHOW_DELETE_CONFIRM";
export const HIDE_DELETE_CONFIRM = "HIDE_DELETE_CONFIRM";

// authentication
export const AUTH_USER = "AUTH_USER";
export const AUTH_USER_START = "AUTH_START";
export const AUTH_USER_COMPLETE = "AUTH_COMPLETE";
export const AUTH_USER_FAILED = "AUTH_FAILED";

export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGOUT_COMPLETE = "AUTH_LOGOUT_COMPLETE";

export const GET_USER_INFO = "GET_USER_INFO";
export const GET_USER_INFO_COMPLETE = "GET_USER_INFO_COMPLETE";
export const GET_USER_INFO_FAILED = "GET_USER_INFO_FAILED";

// projects
export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECTS_START = "GET_PROJECTS_START";
export const GET_PROJECTS_COMPLETE = "GET_PROJECTS_COMPLETE";
export const GET_PROJECTS_FAILED = "GET_PROJECTS_FAILED";

export const ADD_PROJECT = "ADD_PROJECT";
export const ADD_PROJECT_COMPLETE = "ADD_PROJECT_COMPLETE";
export const ADD_PROJECT_FAILED = "ADD_PROJECT_FAILED";

export const EDIT_PROJECT = "EDIT_PROJECT";
export const EDIT_PROJECT_COMPLETE = "EDIT_PROJECT_COMPLETE";
export const EDIT_PROJECT_FAILED = "EDIT_PROJECT_FAILED";

export const COMPLETE_PROJECT = "COMPLETE_PROJECT";
export const COMPLETE_PROJECT_COMPLETE = "COMPLETE_PROJECT_COMPLETE";
export const COMPLETE_PROJECT_FAILED = "COMPLETE_PROJECT_FAILED";

export const DELETE_PROJECT = "DELETE_PROJECT";
export const DELETE_PROJECT_COMPLETE = "DELETE_PROJECT_COMPLETE";
export const DELETE_PROJECT_FAILED = "DELETE_PROJECT_FAILED";

export const SHOW_PROJECT_ADD_FORM = "SHOW_PROJECT_ADD_FORM";
export const HIDE_PROJECT_ADD_FORM = "HIDE_PROJECT_ADD_FORM";
export const SHOW_PROJECT_EDIT_FORM = "SHOW_PROJECT_EDIT_FORM";
export const HIDE_PROJECT_EDIT_FORM = "HIDE_PROJECT_EDIT_FORM";
export const SHOW_PROJECT_DELETE_CONFIRM = "SHOW_PROJECT_DELETE_CONFIRM";
export const HIDE_PROJECT_DELETE_CONFIRM = "HIDE_PROJECT_DELETE_CONFIRM";