// tasks
export const GET_TASKS = "GET_TASKS";
export const GET_TASKS_START = "GET_TASKS_START";
export const GET_TASKS_COMPLETE = "GET_TASKS_COMPLETE";
export const GET_TASKS_FAILED = "GET_TASKS_FAILED";

export const GET_COMPLETED_TASKS = "GET_COMPLETED_TASKS";

export const GET_TOTAL_COUNT = "GET_TOTAL_COUNT";
export const GET_TOTAL_COUNT_COMPLETE = "GET_TOTAL_COUNT_COMPLETE";
export const GET_TOTAL_COUNT_FAILED = "GET_TOTAL_COUNT_FAILED";

export const ADD_TASK = "ADD_TASK";
export const ADD_TASK_START = "ADD_TASK_START";
export const ADD_TASK_COMPLETE = "ADD_TASK_COMPLETE";
export const ADD_TASK_FAILED = "ADD_TASK_FAILED";

export const DELETE_TASK = "DELETE_TASK";
export const DELETE_TASK_START = "DELETE_TASK_START";
export const DELETE_TASK_COMPLETE = "DELETE_TASK_COMPLETE";
export const DELETE_TASK_FAILED = "DELETE_TASK_FAILED";

export const EDIT_TASK = "EDIT_TASK";
export const EDIT_TASK_START = "EDIT_TASK_START";
export const EDIT_TASK_COMPLETE = "EDIT_TASK_COMPLETE";
export const EDIT_TASK_FAILED = "EDIT_TASK_FAILED";

export const COMPLETE_TASK = "COMPLETE_TASK";

export const REARRANGE_TASKS = "REARRANGE_TASKS";
export const REARRANGE_TASKS_START = "REARRANGE_TASKS_START";
// export const REARRANGE_TASK_LISTS = "REARRANGE_TASK_LISTS";
// export const REARRANGE_TASK_LISTS_START = "REARRANGE_TASK_LISTS_START";
export const REARRANGE_TASKS_COMPLETE = "REARRANGE_TASKS_COMPLETE";
export const REARRANGE_TASKS_FAILED = "REARRANGE_TASKS_FAILED";

// forms
export const SHOW_ADD_FORM = "SHOW_ADD_FORM";
export const HIDE_ADD_FORM = "HIDE_ADD_FORM";

export const SHOW_EDIT_FORM = "SHOW_EDIT_FORM";
export const HIDE_EDIT_FORM = "HIDE_EDIT_FORM";